package com.squeeare.hidelockwidgets.data

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Environment
import androidx.documentfile.provider.DocumentFile
import com.google.gson.GsonBuilder
import java.io.File
import java.io.FileOutputStream

class ConfigRepository(private val context: Context) {
    private val gson = GsonBuilder().setPrettyPrinting().create()

    @Suppress("DEPRECATION")
    private val mediaDir = File(
        Environment.getExternalStorageDirectory(),
        "Android/media/com.squeeare.hidelockwidgets"
    )

    private val jsonFile = File(mediaDir, "config.json")

    init { mediaDir.mkdirs() }

    fun load(): DepthConfig {
        if (!jsonFile.exists()) return DepthConfig()
        return runCatching {
            gson.fromJson(jsonFile.readText(), DepthConfig::class.java) ?: DepthConfig()
        }.getOrElse { DepthConfig() }
    }

    fun save(config: DepthConfig) {
        mediaDir.mkdirs()
        jsonFile.writeText(gson.toJson(config))
    }

    fun importImage(uri: Uri, namePrefix: String): String? {
        runCatching {
            context.contentResolver.takePersistableUriPermission(
                uri,
                Intent.FLAG_GRANT_READ_URI_PERMISSION
            )
        }
        mediaDir.mkdirs()
        val docName = DocumentFile.fromSingleUri(context, uri)?.name ?: "$namePrefix.png"
        val ext = docName.substringAfterLast('.', "png")
        mediaDir.listFiles()?.filter { it.name.startsWith(namePrefix) }?.forEach { it.delete() }
        val out = File(mediaDir, "$namePrefix.$ext")
        return try {
            context.contentResolver.openInputStream(uri)?.use { input ->
                FileOutputStream(out).use { output -> input.copyTo(output) }
            }
            out.absolutePath
        } catch (_: Throwable) { null }
    }

    fun applyLegacyConfigWithRoot(config: DepthConfig): Boolean {
        val text = buildLegacyConfig(config)
        val tmp = File(context.cacheDir, "config.txt")
        tmp.writeText(text)
        return runSu(
            "mkdir -p /data/local/tmp/hidelockwidgets && " +
            "cp '${tmp.absolutePath}' /data/local/tmp/hidelockwidgets/config.txt && " +
            "chmod 777 /data/local/tmp/hidelockwidgets && " +
            "chmod 666 /data/local/tmp/hidelockwidgets/config.txt && " +
            "appwidget grantbind --package com.android.systemui --user 0 >/dev/null 2>&1; " +
            "killall com.android.systemui >/dev/null 2>&1; true"
        )
    }

    private fun buildLegacyConfig(config: DepthConfig): String {
        val widgets = config.widgets.filter { it.visible }
        val first = widgets.firstOrNull() ?: WidgetConfig()
        return buildString {
            appendLine("# Generated by HideLockWidgets UI")
            appendLine("widgets=${widgets.size}")
            widgets.forEachIndexed { index, w ->
                val n = index + 1
                appendLine("widget.$n.provider=${w.provider}")
                appendLine("widget.$n.x_dp=${w.xDp}")
                appendLine("widget.$n.y_dp=${w.yDp}")
                appendLine("widget.$n.width_dp=${w.widthDp}")
                appendLine("widget.$n.height_dp=${w.heightDp}")
                appendLine("widget.$n.scale_percent=${w.scalePercent}")
                appendLine("widget.$n.live_mode=${w.liveMode}")
                appendLine("widget.$n.snapshot=${w.snapshot}")
            }
            appendLine()
            appendLine("provider=${first.provider}")
            appendLine("widget_id=${first.id}")
            appendLine("x_dp=${first.xDp}")
            appendLine("y_dp=${first.yDp}")
            appendLine("width_dp=${first.widthDp}")
            appendLine("height_dp=${first.heightDp}")
            appendLine("scale_percent=${first.scalePercent}")
            appendLine("live_mode=${first.liveMode}")
            appendLine("snapshot=${first.snapshot}")
            appendLine("depth_enabled=${config.depthEnabled}")
            appendLine("depth_background=${config.backgroundPath ?: ""}")
            appendLine("depth_foreground=${config.foregroundPath ?: ""}")
        }
    }

    private fun runSu(command: String): Boolean {
        return try {
            val p = Runtime.getRuntime().exec(arrayOf("su", "-c", command))
            p.waitFor() == 0
        } catch (_: Throwable) { false }
    }
}
